FROM python:3.9-slim

WORKDIR /app

COPY streamlit_app/requirements.txt ./
RUN apt update
RUN apt-get install -y libglib2.0-0 libsm6 libxrender1 libxext6
RUN pip install -r requirements.txt
RUN pip uninstall --yes opencv-python
RUN pip install opencv-python-headless python-multipart

# COPY streamlit_app/ .

EXPOSE 8501

CMD ["streamlit", "run", "app.py"]