FROM python:3.9-slim

WORKDIR /app

COPY service/requirements.txt ./
RUN apt update
RUN apt-get install -y libglib2.0-0 libsm6 libxrender1 libxext6
RUN pip install -r requirements.txt
RUN pip install uvicorn tensorflow==2.18.0 python-multipart
RUN pip uninstall --yes opencv-python
RUN pip install opencv-python-headless
# COPY service/ .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]